name: experts_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bounceable: ^1.1.0
  connectivity_plus: ^2.3.4
  url_launcher: ^6.0.26
  intl: ^0.19.0
  equatable: ^2.0.3
  multiselect_formfield: ^0.1.7
  syncfusion_flutter_charts: ^25.1.42+1
  screenshot: any
  flutter_screenutil: ^5.9.0
  responsive_builder: ^0.4.0
  animate_do: ^3.3.4
  dio: ^5.4.2+1
  dartz: ^0.10.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.2
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3
  lottie: ^3.1.0
  cupertino_icons: ^1.0.6
  multi_circular_slider: ^1.1.0
  excel: ^4.0.3
  flutter_riverpod: ^2.0.0
  pdf: ^3.5.0
  printing: ^5.9.0
  flutter_otp_text_field: ^1.1.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf

    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
        - asset: assets/fonts/NotoNaskhArabic-SemiBold.ttf
        - asset: assets/fonts/NotoNaskhArabic-Medium.ttf
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
