// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBcghEthJHQRUxH-S__Dv2wi39lzTRI_o',
    appId: '1:33164804905:web:6f26a521835db64a25ad38',
    messagingSenderId: '33164804905',
    projectId: 'financial-app-activation',
    authDomain: 'financial-app-activation.firebaseapp.com',
    storageBucket: 'financial-app-activation.appspot.com',
    measurementId: 'G-NQ731RVXBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBjHElksy6vRGBXZ0kL_iWtm7YBBv5bQU',
    appId: '1:33164804905:android:aaecae45293edefc25ad38',
    messagingSenderId: '33164804905',
    projectId: 'financial-app-activation',
    storageBucket: 'financial-app-activation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhsGSI5zFmWI6HOK75o5H3q3SCjdoZ0so',
    appId: '1:33164804905:ios:c4c6454d3c4ee10425ad38',
    messagingSenderId: '33164804905',
    projectId: 'financial-app-activation',
    storageBucket: 'financial-app-activation.appspot.com',
    iosBundleId: 'com.example.expertsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhsGSI5zFmWI6HOK75o5H3q3SCjdoZ0so',
    appId: '1:33164804905:ios:c4c6454d3c4ee10425ad38',
    messagingSenderId: '33164804905',
    projectId: 'financial-app-activation',
    storageBucket: 'financial-app-activation.appspot.com',
    iosBundleId: 'com.example.expertsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBcghEthJHQRUxH-S__Dv2wi39lzTRI_o',
    appId: '1:33164804905:web:fc7be283b4701d5725ad38',
    messagingSenderId: '33164804905',
    projectId: 'financial-app-activation',
    authDomain: 'financial-app-activation.firebaseapp.com',
    storageBucket: 'financial-app-activation.appspot.com',
    measurementId: 'G-JWT51ZBRGB',
  );

}